### ISSUE TITLE
Use parameters

### ISSUE THREAD

**Issue by ice1000** [LaufferN/HoTT-Arend#1]
https://github.com/LaufferN/HoTT-Arend/blob/14319684c424dd2cadaca89b9c61baa4dbdf3f33/src/chapter1/definitions/def.ard#L1-L3

```arend
-- standard refl type 
\func refl (A : \Type)  (a : A) => path (\lam i => a)
```

**Comment by niklaslauffer** [comment]
Thanks for the corrections!
