### ISSUE TITLE
This is not a dependent product type

### ISSUE THREAD

**Issue by ice1000** [LaufferN/HoTT-Arend#2]
https://github.com/LaufferN/HoTT-Arend/blob/14319684c424dd2cadaca89b9c61baa4dbdf3f33/src/chapter1/definitions/def.ard#L11-L12

This is a simple product type.
A dependent product type is like this:

```arend
\func \infix 6 xx (A : \Type) (B : A -> \Type) : \Type => \Sigma (x : A) (B x) 
```

**Comment by ice1000** [comment]
Any reasons for closing?

**Comment by niklaslauffer** [comment]
I changed the comment to reflect your clarification. Thanks for the correction!

**Comment by ice1000** [comment]
You can type `close #2` in your commit messages to close issue of number 2

**Comment by niklaslauffer** [comment]
Very cool, I'll try that out next time.
