### ISSUE TITLE
Refl is not a type

### ISSUE THREAD

**Issue by ice1000** [LaufferN/HoTT-Arend#4]
https://github.com/LaufferN/HoTT-Arend/blob/7bc1e69abcf98d940893d4db26a9bb15daa24858/src/chapter1/definitions/def.ard#L76
The comment states a wrong fact

**Comment by tewaro** [comment]
I'm hoping this commit is more correct: 6d405e4.

**Comment by ice1000** [comment]
Maybe "proof"
