### ISSUE TITLE
Use arend-lib?

### ISSUE THREAD

**Issue by ice1000** [LaufferN/HoTT-Arend#5]
Lots of definitions here are available in arend-lib. Is it intended to not use the standard library?

**Comment by tewaro** [comment]
For the most part yes it is intended to not use the standard library so exploration of the definitions follows the HoTT book closely, and is done explicitly.

**Comment by ice1000** [comment]
How about styling? Arend has a code formatter (Ctrl+Alt+L) and don't prefer adding parentheses in every arguments applied (like in Haskell), it seems this lib respect neither the formatter nor the parentheses thing

**Comment by tewaro** [comment]
We didn't know about the code formatter but we'll update that.
The parentheses are just my fault for being careless.

**Comment by ice1000** [comment]
How do you like Arend?

**Comment by tewaro** [comment]
It's interesting, I prefer it over Coq, but I haven't done much Agda. 
I like how it interfaces with Intellij and the feature set for an incomplete goal.
It makes defining things like the inductor make a bit more sense in the context of type theory.

**Comment by tewaro** [comment]
This issue should be fixed now with b423b3f.

**Comment by ice1000** [comment]
Cool. What's the purpose of this repo? Is it for practice or for some courses?

**Comment by tewaro** [comment]
It's more to provide a structure to go through reading the HoTT book.
We are creating this to back a reading group at UT.

**Comment by ice1000** [comment]
Ok, I'm happy to see UT is using Arend ^v^.
Fyi, we also prefer capitalized package name. For general Arend discussion you can refer to the gitter channel (link in official repo readme). The standard library is a good resource for styling reference. Ask me anything about Arend and I'm willing to help.

**Comment by tewaro** [comment]
We will try and get that changed.
